load("//bazel:proto.bzl", "ts_proto_library")

package(default_visibility = ["//visibility:public"])

ts_proto_library(
    name = "descriptor_ts_proto",
    proto = "@com_google_protobuf//:descriptor_proto",
)

ts_proto_library(
    name = "any_ts_proto",
    proto = "@com_google_protobuf//:any_proto",
)
