load("//bazel:proto.bzl", "fhir_wrapped_ts_proto_library")

package(default_visibility = ["//visibility:public"])

fhir_wrapped_ts_proto_library(
    name = "descriptor_ts_proto",
    proto = "@com_google_protobuf//:descriptor_proto",
)

fhir_wrapped_ts_proto_library(
    name = "any_ts_proto",
    proto = "@com_google_protobuf//:any_proto",
)
