load("//bazel:proto.bzl", "fhir_wrapped_ts_proto_library", "fhir_wrapped_ts_proto_library_2")

package(default_visibility = ["//visibility:public"])

fhir_wrapped_ts_proto_library(
    name = "descriptor_ts_proto",
    proto = "@com_google_protobuf//:descriptor_proto",
)

fhir_wrapped_ts_proto_library(
    name = "any_ts_proto",
    proto = "@com_google_protobuf//:any_proto",
)

fhir_wrapped_ts_proto_library(
    name = "empty_ts_proto",
    proto = "@com_google_protobuf//:empty_proto",
)

fhir_wrapped_ts_proto_library(
    name = "struct_ts_proto",
    proto = "@com_google_protobuf//:struct_proto",
)

fhir_wrapped_ts_proto_library_2(
    name = "descriptor_ts_proto_2",
    proto = "@com_google_protobuf//:descriptor_proto",
)

fhir_wrapped_ts_proto_library_2(
    name = "any_ts_proto_2",
    proto = "@com_google_protobuf//:any_proto",
)

fhir_wrapped_ts_proto_library_2(
    name = "empty_ts_proto_2",
    proto = "@com_google_protobuf//:empty_proto",
)

fhir_wrapped_ts_proto_library_2(
    name = "struct_ts_proto_2",
    proto = "@com_google_protobuf//:struct_proto",
)
